name: Deploy Infrastructure

on:
  push:
    branches:
      - master

env:
  TF_CLOUD_ORGANIZATION: "WhiteWolf21"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-push-github-static-app"
  TF_VAR_gh_token: ${{ secrets.TOKEN }}
  CONFIG_DIRECTORY: "./"

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Terraform Init
        run: terraform init
        id: init
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        id: apply
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}