name: Deploy Infrastructure

on:
  push:
    branches:
      - master

env:
  TF_CLOUD_ORGANIZATION: "WhiteWolf21"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-push-github-static-app"
  CONFIG_DIRECTORY: "./"

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      with:
        gh_token: ${{ secrets.TOKEN }}