name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      run: terraform init

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0